/* PLAYERS WHO HAVE PLAYED ATLEAST 10 MATCHES */

SELECT * FROM `aditipaitandy4172.men_IPL.2019_Batsmen` WHERE Mat >10  LIMIT 10 ;

/* NAMES AND THE TEAMS OF ALL BATSMEN WHO PLAYED IN 2018 */

SELECT Player, Team FROM `men_IPL.2018_Batsmen` ;

/* TEAMS THAT ARE REPRESENTED BY ALL THE BATSMEN FROM 2019 */

SELECT DISTINCT Team FROM `men_IPL.2019_Batsmen` ;

/* TOTAL RUNS SCORED BY ALL THE BATSMEN IN 2018 */

SELECT SUM(Runs) AS TotalRuns FROM `men_IPL.2018_Batsmen` ;

/* LIST THE CHENNAI BATSMEN AND TOTAL NUMBER OF MATCHES PLAYED IN 2019 */

SELECT Player , Mat  FROM `men_IPL.2019_Batsmen` WHERE Team = "Chennai Super Kings";

/* PLAYERS WHO TOOK 4 WICKET HAUL(S) IN 2018 */

SELECT Player , Team , `4w`  FROM `men_IPL.2018_Bowlers` WHERE `4w` > 0  ;

/* THE NAMES OF TEAMS AND THE BOWLERS FROM 2019 */

SELECT Player , Team FROM `men_IPL.2019_Bowlers` ;

/* HAD ATLEAST ONE BOWLER WHO TOOK ONE 4W in 2018 */

SELECT DISTINCT Team , `4w` FROM `men_IPL.2018_Bowlers` WHERE `4w` >= 1 ;

/* THE NAME AND THE RUNS INCURRED BY THE BOWLERS IN 2018 */

SELECT Player , Runs FROM `men_IPL.2018_Bowlers` ORDER BY Runs LIMIT 3 ;

/* NAME TWO BOWLERS WHO TOOK MOST NUMBER OF WICKETS */

SELECT Player, Wkts FROM `men_IPL.2018_Bowlers` ORDER BY Wkts DESC LIMIT 2;

/* THE NAMES AND TEAMS OF ALL ALLROUNDERS IN THE YEAR 2018 */

SELECT a.Player, a.Team FROM `men_IPL.2018_Bowlers` AS a INNER JOIN `men_IPL.2018_Batsmen` AS b ON a.Player = b.Player;

/* THE NAMES AND TEAMS OF ALL ALLROUNDERS IN THE YEAR 2019 */

SELECT p.Player, p.Team FROM `men_IPL.2019_Batsmen` AS p INNER JOIN `men_IPL.2019_Bowlers` AS a ON p.Player = a.Player;

/* THE LIST OF BATSMEN WHO PLAYED IN BOTH 2018 AND 2019 SEASONS */

SELECT a.Player FROM `men_IPL.2019_Batsmen` AS a INNER JOIN `men_IPL.2018_Batsmen` AS b ON a.Player = b.Player;

/* TOTAL NUMBER OF BATSMEN IN EACH TEAM FOR THE 2019 SEASON */

SELECT Team, COUNT(Player) AS TotalCount FROM `men_IPL.2019_Batsmen` GROUP BY Team;

/* THE NUMBER OF BATSMEN IN EACH TEAM FOR 2019 SORTED FROM HIGHEST TO LOWEST */

SELECT Team, COUNT(Player) AS TotalCount FROM `men_IPL.2019_Batsmen` GROUP BY Team ORDER BY TotalCount DESC;

/* NUMBER OF BOWLERS PER TEAM WHO TOOK AT LEAST ONE 4-WICKET HAUL IN 2018 */

SELECT Team, COUNT(Player) AS TotalCount FROM `men_IPL.2018_Bowlers` WHERE `4w` >= 1 GROUP BY Team;

/* THE TOP 2 TEAMS WITH THE HIGHEST NUMBER OF BOWLERS IN THE 2018 SEASON */

SELECT Team, COUNT(Player) AS TotalCount FROM `men_IPL.2018_Bowlers` GROUP BY Team ORDER BY COUNT(Player) DESC LIMIT 2;

/* THE BOWLER WHO TOOK THE MAXIMUM NUMBER OF WICKETS IN THE 2018 SEASON */

SELECT Player, Wkts FROM `men_IPL.2018_Bowlers` ORDER BY Wkts DESC LIMIT 1;

/* 1. WHICH BOWLER TOOK THE MOST WICKETS IN THE 2018 SEASON? */

SELECT Player, Wkts FROM `men_IPL.2018_Bowlers` ORDER BY Wkts DESC LIMIT 1;

/* 2. WHICH BATSMEN SCORED THE MOST RUNS IN THE 2018 SEASON WHILE MAINTAINING AN AVERAGE STRIKE RATE OF AT LEAST 130? */

SELECT Player, Runs, S_R FROM `men_IPL.2018_Batsmen` WHERE S_R >= 130 ORDER BY Runs DESC LIMIT 1;

/* 3. WHICH BOWLERS TOOK THE MOST WICKETS IN THE 2018 SEASON WHILE MAINTAINING AN ECONOMY RATE OF LESS THAN 7 RUNS PER OVER? */

SELECT Player, Wkts, E_R FROM `men_IPL.2018_Bowlers` WHERE E_R < 7 ORDER BY Wkts DESC;

/* 4. WHICH BATSMEN SCORED THE MOST RUNS ACROSS BOTH 2018 AND 2019 SEASONS? */

SELECT a.Player, (SUM(a.Runs) + SUM(b.Runs)) AS CombinedRuns FROM `men_IPL.2018_Batsmen` AS a INNER JOIN `men_IPL.2019_Batsmen` AS b ON a.Player = b.Player GROUP BY a.Player ORDER BY CombinedRuns DESC LIMIT 1;

/* 5. WHICH BATSMEN HAS HIT THE MAXIMUM NUMBER OF BOUNDARIES IN 2018, COMBINING 4S AND 6S? */

SELECT Player, (`4s` + `6s`) AS TotalBoundaries FROM `men_IPL.2018_Batsmen` ORDER BY TotalBoundaries DESC LIMIT 1;

/* 6. NAME THE BOWLERS WHO HAVE GOT 4 WICKETS HAUL IN 2019 */

SELECT Player, Team, `4w` FROM `men_IPL.2019_Bowlers` WHERE `4w` >= 1;

/* 7. NAME 5 SUCH BOWLERS WHO BOWLED THE LEAST NUMBER OF OVERS IN 2018 */

SELECT Player, Overs FROM `men_IPL.2018_Bowlers` ORDER BY Overs ASC LIMIT 5;

/* 8. WHICH TEAM SCORED THE MAXIMUM NUMBER OF RUNS IN 2019? */

SELECT Team, SUM(Runs) AS TeamTotalRuns FROM `men_IPL.2019_Batsmen` GROUP BY Team ORDER BY TeamTotalRuns DESC LIMIT 1;

/* 9. NAME THE BATSMEN WHO HAS HIT MAXIMUM HALF CENTURIES, BOTH THE YEARS COMBINED */

SELECT a.Player, (a.`50s` + b.`50s`) AS TotalHalfCenturies FROM `men_IPL.2018_Batsmen` AS a INNER JOIN `men_IPL.2019_Batsmen` AS b ON a.Player = b.Player ORDER BY TotalHalfCenturies DESC LIMIT 1;